/* Generated by Yosys 0.56+165 (git sha1 4926e846f, clang++ 18.1.8 -fPIC -O3) */

module mux2to1_gate(in0, in1, sel, out);
  input [7:0] in0;
  wire [7:0] in0;
  input [7:0] in1;
  wire [7:0] in1;
  input sel;
  wire sel;
  output [7:0] out;
  wire [7:0] out;
  MUX2_X1 _0_ (
    .A(in0[0]),
    .B(in1[0]),
    .S(sel),
    .Z(out[0])
  );
  MUX2_X1 _1_ (
    .A(in0[1]),
    .B(in1[1]),
    .S(sel),
    .Z(out[1])
  );
  MUX2_X1 _2_ (
    .A(in0[2]),
    .B(in1[2]),
    .S(sel),
    .Z(out[2])
  );
  MUX2_X1 _3_ (
    .A(in0[3]),
    .B(in1[3]),
    .S(sel),
    .Z(out[3])
  );
  MUX2_X1 _4_ (
    .A(in0[4]),
    .B(in1[4]),
    .S(sel),
    .Z(out[4])
  );
  MUX2_X1 _5_ (
    .A(in0[5]),
    .B(in1[5]),
    .S(sel),
    .Z(out[5])
  );
  MUX2_X1 _6_ (
    .A(in0[6]),
    .B(in1[6]),
    .S(sel),
    .Z(out[6])
  );
  MUX2_X1 _7_ (
    .A(in0[7]),
    .B(in1[7]),
    .S(sel),
    .Z(out[7])
  );
endmodule
