/* Generated by Yosys 0.63 (git sha1 d3e297fcd, g++ 12.2.0-14+deb12u1 -fPIC -O3) [the-openroad-project/yosys] */

(* hdlname = "mux2to1" *)
(* dynports =  1  *)
(* top =  1  *)
(* src = "./designs/src/mux2to1/mux2to1.v:8.1-20.10" *)
module mux2to1(in0, in1, sel, out);
  (* src = "./designs/src/mux2to1/mux2to1.v:11.34-11.37" *)
  input [7:0] in0;
  wire [7:0] in0;
  (* src = "./designs/src/mux2to1/mux2to1.v:12.34-12.37" *)
  input [7:0] in1;
  wire [7:0] in1;
  (* src = "./designs/src/mux2to1/mux2to1.v:13.35-13.38" *)
  input sel;
  wire sel;
  (* src = "./designs/src/mux2to1/mux2to1.v:14.34-14.37" *)
  output [7:0] out;
  wire [7:0] out;
  wire _0_;
  BUF_X4 _1_ (
    .A(sel),
    .Z(_0_)
  );
  MUX2_X1 _2_ (
    .A(in0[6]),
    .B(in1[6]),
    .S(_0_),
    .Z(out[6])
  );
  MUX2_X1 _3_ (
    .A(in0[4]),
    .B(in1[4]),
    .S(_0_),
    .Z(out[4])
  );
  MUX2_X1 _4_ (
    .A(in0[3]),
    .B(in1[3]),
    .S(_0_),
    .Z(out[3])
  );
  MUX2_X1 _5_ (
    .A(in0[2]),
    .B(in1[2]),
    .S(_0_),
    .Z(out[2])
  );
  MUX2_X1 _6_ (
    .A(in0[1]),
    .B(in1[1]),
    .S(_0_),
    .Z(out[1])
  );
  MUX2_X1 _7_ (
    .A(in0[0]),
    .B(in1[0]),
    .S(_0_),
    .Z(out[0])
  );
  MUX2_X1 _8_ (
    .A(in0[7]),
    .B(in1[7]),
    .S(_0_),
    .Z(out[7])
  );
  MUX2_X1 _9_ (
    .A(in0[5]),
    .B(in1[5]),
    .S(_0_),
    .Z(out[5])
  );
endmodule
