/* Generated by Yosys 0.63 (git sha1 d3e297fcd, g++ 12.2.0-14+deb12u1 -fPIC -O3) [the-openroad-project/yosys] */

(* hdlname = "lfsr_4bit" *)
(* top =  1  *)
(* src = "/opt/OpenROAD-flow-scripts/flow/designs/src/lfsr_4bit/lfsr_4bit.v:2.1-24.10" *)
module lfsr_4bit(clk, res, y);
  (* src = "/opt/OpenROAD-flow-scripts/flow/designs/src/lfsr_4bit/lfsr_4bit.v:3.18-3.21" *)
  input clk;
  wire clk;
  (* src = "/opt/OpenROAD-flow-scripts/flow/designs/src/lfsr_4bit/lfsr_4bit.v:4.18-4.21" *)
  input res;
  wire res;
  (* src = "/opt/OpenROAD-flow-scripts/flow/designs/src/lfsr_4bit/lfsr_4bit.v:5.18-5.19" *)
  output y;
  wire y;
  (* src = "/opt/OpenROAD-flow-scripts/flow/designs/src/lfsr_4bit/lfsr_4bit.v:20.17-20.28|/opt/OpenROAD-flow-scripts/tools/install/yosys/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire _0_;
  (* unused_bits = "0" *)
  wire _1_;
  (* unused_bits = "0" *)
  wire _2_;
  (* unused_bits = "0" *)
  wire _3_;
  (* unused_bits = "0" *)
  wire _4_;
  (* src = "/opt/OpenROAD-flow-scripts/flow/designs/src/lfsr_4bit/lfsr_4bit.v:9.11-9.12" *)
  wire \d[1] ;
  (* src = "/opt/OpenROAD-flow-scripts/flow/designs/src/lfsr_4bit/lfsr_4bit.v:9.11-9.12" *)
  wire \d[2] ;
  (* src = "/opt/OpenROAD-flow-scripts/flow/designs/src/lfsr_4bit/lfsr_4bit.v:9.11-9.12" *)
  wire \d[3] ;
  XOR2_X1 _5_ (
    .A(\d[3] ),
    .B(y),
    .Z(_0_)
  );
  (* src = "/opt/OpenROAD-flow-scripts/flow/designs/src/lfsr_4bit/lfsr_4bit.v:13.1-22.4" *)
  DFFS_X1 \d[0]$_DFF_PN1_  (
    .CK(clk),
    .D(\d[1] ),
    .Q(y),
    .QN(_2_),
    .SN(res)
  );
  (* src = "/opt/OpenROAD-flow-scripts/flow/designs/src/lfsr_4bit/lfsr_4bit.v:13.1-22.4" *)
  DFFS_X1 \d[1]$_DFF_PN1_  (
    .CK(clk),
    .D(\d[2] ),
    .Q(\d[1] ),
    .QN(_3_),
    .SN(res)
  );
  (* src = "/opt/OpenROAD-flow-scripts/flow/designs/src/lfsr_4bit/lfsr_4bit.v:13.1-22.4" *)
  DFFS_X1 \d[2]$_DFF_PN1_  (
    .CK(clk),
    .D(\d[3] ),
    .Q(\d[2] ),
    .QN(_1_),
    .SN(res)
  );
  (* src = "/opt/OpenROAD-flow-scripts/flow/designs/src/lfsr_4bit/lfsr_4bit.v:13.1-22.4" *)
  DFFS_X1 \d[3]$_DFF_PN1_  (
    .CK(clk),
    .D(_0_),
    .Q(\d[3] ),
    .QN(_4_),
    .SN(res)
  );
endmodule
