/* Generated by Yosys 0.56+165 (git sha1 4926e846f, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "uart_tx_combined.v:81.1-373.10" *)
module uart_tx(PCLK, PRESETn, PWDATA, tx_fifo_push, LCR, enable, tx_fifo_empty, tx_fifo_full, tx_fifo_count, busy, TXD);
  (* src = "uart_tx_combined.v:82.24-82.28" *)
  input PCLK;
  wire PCLK;
  (* src = "uart_tx_combined.v:83.24-83.31" *)
  input PRESETn;
  wire PRESETn;
  (* src = "uart_tx_combined.v:84.24-84.30" *)
  input [7:0] PWDATA;
  wire [7:0] PWDATA;
  (* src = "uart_tx_combined.v:85.24-85.36" *)
  input tx_fifo_push;
  wire tx_fifo_push;
  (* src = "uart_tx_combined.v:86.24-86.27" *)
  input [7:0] LCR;
  wire [7:0] LCR;
  (* src = "uart_tx_combined.v:87.24-87.30" *)
  input enable;
  wire enable;
  (* src = "uart_tx_combined.v:88.24-88.37" *)
  output tx_fifo_empty;
  wire tx_fifo_empty;
  (* src = "uart_tx_combined.v:89.24-89.36" *)
  output tx_fifo_full;
  wire tx_fifo_full;
  (* src = "uart_tx_combined.v:90.24-90.37" *)
  output [4:0] tx_fifo_count;
  wire [4:0] tx_fifo_count;
  (* src = "uart_tx_combined.v:91.24-91.28" *)
  output busy;
  reg busy;
  (* src = "uart_tx_combined.v:92.24-92.27" *)
  output TXD;
  reg TXD;
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  wire _000_;
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  (* unused_bits = "0 1 2 3 4" *)
  wire [7:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  (* force_downto = 32'd1 *)
  (* src = "uart_tx_combined.v:291.20-291.20|uart_tx_combined.v:150.13-359.20|/opt/oss-cad-suite/lib/../share/yosys/techmap.v:576.21-576.22" *)
  wire [0:0] _112_;
  (* force_downto = 32'd1 *)
  (* src = "uart_tx_combined.v:328.20-328.20|uart_tx_combined.v:150.13-359.20|/opt/oss-cad-suite/lib/../share/yosys/techmap.v:576.21-576.22" *)
  wire [0:0] _113_;
  (* force_downto = 32'd1 *)
  (* src = "uart_tx_combined.v:328.20-328.20|uart_tx_combined.v:150.13-359.20|/opt/oss-cad-suite/lib/../share/yosys/techmap.v:576.21-576.22" *)
  wire [3:0] _114_;
  (* force_downto = 32'd1 *)
  (* src = "uart_tx_combined.v:328.20-328.20|uart_tx_combined.v:150.13-359.20|/opt/oss-cad-suite/lib/../share/yosys/techmap.v:576.21-576.22" *)
  wire [3:0] _115_;
  (* src = "uart_tx_combined.v:110.17-110.28" *)
  reg [3:0] bit_counter;
  (* src = "uart_tx_combined.v:114.17-114.31" *)
  reg half_stop_flag;
  reg [5:0] lcr_latched;
  (* src = "uart_tx_combined.v:112.17-112.28" *)
  reg pop_tx_fifo;
  (* src = "uart_tx_combined.v:111.17-111.26" *)
  reg [7:0] tx_buffer;
  (* src = "uart_tx_combined.v:119.17-119.32" *)
  wire [4:0] tx_fifo_count_w;
  (* src = "uart_tx_combined.v:117.17-117.32" *)
  wire tx_fifo_empty_w;
  (* src = "uart_tx_combined.v:118.17-118.31" *)
  wire tx_fifo_full_w;
  (* src = "uart_tx_combined.v:116.17-116.28" *)
  wire [7:0] tx_fifo_out;
  (* src = "uart_tx_combined.v:109.17-109.25" *)
  reg [3:0] tx_state;
  INV_X1 _116_ (
    .A(tx_state[0]),
    .ZN(_064_)
  );
  INV_X1 _117_ (
    .A(tx_state[3]),
    .ZN(_065_)
  );
  INV_X1 _118_ (
    .A(bit_counter[3]),
    .ZN(_066_)
  );
  INV_X1 _119_ (
    .A(enable),
    .ZN(_067_)
  );
  INV_X1 _120_ (
    .A(tx_fifo_empty_w),
    .ZN(_068_)
  );
  INV_X1 _121_ (
    .A(lcr_latched[1]),
    .ZN(_069_)
  );
  NAND2_X1 _122_ (
    .A1(tx_state[2]),
    .A2(tx_state[3]),
    .ZN(_070_)
  );
  NOR2_X1 _123_ (
    .A1(tx_state[1]),
    .A2(tx_state[0]),
    .ZN(_071_)
  );
  OR2_X1 _124_ (
    .A1(tx_state[1]),
    .A2(tx_state[0]),
    .ZN(_072_)
  );
  NOR2_X1 _125_ (
    .A1(_070_),
    .A2(_072_),
    .ZN(_073_)
  );
  OR2_X1 _126_ (
    .A1(_070_),
    .A2(_072_),
    .ZN(_074_)
  );
  NAND2_X1 _127_ (
    .A1(tx_state[1]),
    .A2(_064_),
    .ZN(_075_)
  );
  NOR2_X1 _128_ (
    .A1(tx_state[2]),
    .A2(_075_),
    .ZN(_076_)
  );
  NOR2_X1 _129_ (
    .A1(tx_state[2]),
    .A2(_065_),
    .ZN(_077_)
  );
  OR2_X1 _130_ (
    .A1(tx_state[2]),
    .A2(_065_),
    .ZN(_078_)
  );
  NAND2_X1 _131_ (
    .A1(tx_state[3]),
    .A2(_076_),
    .ZN(_079_)
  );
  NAND2_X1 _132_ (
    .A1(tx_state[1]),
    .A2(tx_state[0]),
    .ZN(_080_)
  );
  NOR2_X1 _133_ (
    .A1(_078_),
    .A2(_080_),
    .ZN(_081_)
  );
  OR2_X1 _134_ (
    .A1(_078_),
    .A2(_080_),
    .ZN(_082_)
  );
  OAI211_X1 _135_ (
    .A(tx_state[1]),
    .B(_077_),
    .C1(lcr_latched[2]),
    .C2(_064_),
    .ZN(_083_)
  );
  AND3_X1 _136_ (
    .A1(bit_counter[1]),
    .A2(bit_counter[0]),
    .A3(bit_counter[2]),
    .ZN(_084_)
  );
  AND2_X1 _137_ (
    .A1(bit_counter[3]),
    .A2(_084_),
    .ZN(_085_)
  );
  NAND2_X1 _138_ (
    .A1(bit_counter[3]),
    .A2(_084_),
    .ZN(_086_)
  );
  AOI21_X1 _139_ (
    .A(_073_),
    .B1(_077_),
    .B2(tx_state[1]),
    .ZN(_087_)
  );
  OAI22_X1 _140_ (
    .A1(_082_),
    .A2(_085_),
    .B1(_087_),
    .B2(enable),
    .ZN(_088_)
  );
  AOI21_X1 _141_ (
    .A(_088_),
    .B1(_083_),
    .B2(_074_),
    .ZN(_002_)
  );
  NOR2_X1 _142_ (
    .A1(tx_state[2]),
    .A2(tx_state[3]),
    .ZN(_089_)
  );
  NAND2_X1 _143_ (
    .A1(_071_),
    .A2(_089_),
    .ZN(_090_)
  );
  NOR3_X1 _144_ (
    .A1(_067_),
    .A2(tx_fifo_empty_w),
    .A3(_090_),
    .ZN(_000_)
  );
  NOR2_X1 _145_ (
    .A1(tx_state[3]),
    .A2(_075_),
    .ZN(_091_)
  );
  NAND2_X1 _146_ (
    .A1(tx_state[2]),
    .A2(_065_),
    .ZN(_092_)
  );
  NOR2_X1 _147_ (
    .A1(_075_),
    .A2(_092_),
    .ZN(_093_)
  );
  OR2_X1 _148_ (
    .A1(_075_),
    .A2(_092_),
    .ZN(_094_)
  );
  NOR2_X1 _149_ (
    .A1(lcr_latched[0]),
    .A2(lcr_latched[1]),
    .ZN(_095_)
  );
  OR2_X1 _150_ (
    .A1(_094_),
    .A2(_095_),
    .ZN(_096_)
  );
  AOI21_X1 _151_ (
    .A(_090_),
    .B1(_068_),
    .B2(enable),
    .ZN(_097_)
  );
  AOI21_X1 _152_ (
    .A(_097_),
    .B1(_093_),
    .B2(_086_),
    .ZN(_098_)
  );
  NAND2_X1 _153_ (
    .A1(_096_),
    .A2(_098_),
    .ZN(_099_)
  );
  NAND3_X1 _154_ (
    .A1(tx_state[1]),
    .A2(tx_state[2]),
    .A3(_065_),
    .ZN(_100_)
  );
  NOR2_X1 _155_ (
    .A1(_064_),
    .A2(_100_),
    .ZN(_101_)
  );
  NAND2_X1 _156_ (
    .A1(enable),
    .A2(_085_),
    .ZN(_102_)
  );
  NOR2_X1 _157_ (
    .A1(enable),
    .A2(_094_),
    .ZN(_103_)
  );
  NAND2_X1 _158_ (
    .A1(lcr_latched[0]),
    .A2(_069_),
    .ZN(_104_)
  );
  OAI21_X1 _159_ (
    .A(_101_),
    .B1(_102_),
    .B2(_104_),
    .ZN(_105_)
  );
  OAI21_X1 _160_ (
    .A(_105_),
    .B1(_094_),
    .B2(enable),
    .ZN(_106_)
  );
  NOR2_X1 _161_ (
    .A1(tx_state[1]),
    .A2(_078_),
    .ZN(_107_)
  );
  NOR2_X1 _162_ (
    .A1(_072_),
    .A2(_078_),
    .ZN(_108_)
  );
  NAND2_X1 _163_ (
    .A1(_102_),
    .A2(_108_),
    .ZN(_109_)
  );
  INV_X1 _164_ (
    .A(_109_),
    .ZN(_110_)
  );
  NOR2_X1 _165_ (
    .A1(lcr_latched[0]),
    .A2(_069_),
    .ZN(_111_)
  );
  NAND2_X1 _166_ (
    .A1(_108_),
    .A2(_111_),
    .ZN(_009_)
  );
  AND3_X1 _167_ (
    .A1(_090_),
    .A2(_100_),
    .A3(_009_),
    .ZN(_010_)
  );
  NOR4_X1 _168_ (
    .A1(_099_),
    .A2(_106_),
    .A3(_110_),
    .A4(_010_),
    .ZN(_003_)
  );
  AOI211_X1 _169_ (
    .A(_099_),
    .B(_106_),
    .C1(_100_),
    .C2(_090_),
    .ZN(_004_)
  );
  AOI211_X1 _170_ (
    .A(_099_),
    .B(_103_),
    .C1(_090_),
    .C2(_094_),
    .ZN(_005_)
  );
  AOI21_X1 _171_ (
    .A(_073_),
    .B1(_090_),
    .B2(_070_),
    .ZN(_011_)
  );
  INV_X1 _172_ (
    .A(_011_),
    .ZN(_008_)
  );
  OAI221_X1 _173_ (
    .A(enable),
    .B1(_070_),
    .B2(_071_),
    .C1(_090_),
    .C2(_068_),
    .ZN(_012_)
  );
  INV_X1 _174_ (
    .A(_012_),
    .ZN(_006_)
  );
  NOR3_X1 _175_ (
    .A1(lcr_latched[0]),
    .A2(lcr_latched[1]),
    .A3(half_stop_flag),
    .ZN(_013_)
  );
  NAND3_X1 _176_ (
    .A1(_066_),
    .A2(_084_),
    .A3(_013_),
    .ZN(_014_)
  );
  AND2_X1 _177_ (
    .A1(_073_),
    .A2(_014_),
    .ZN(_015_)
  );
  NOR2_X1 _178_ (
    .A1(_072_),
    .A2(_092_),
    .ZN(_016_)
  );
  NOR3_X1 _179_ (
    .A1(tx_state[2]),
    .A2(tx_state[3]),
    .A3(_080_),
    .ZN(_017_)
  );
  NOR2_X1 _180_ (
    .A1(_016_),
    .A2(_017_),
    .ZN(_018_)
  );
  NOR3_X1 _181_ (
    .A1(_076_),
    .A2(_016_),
    .A3(_017_),
    .ZN(_019_)
  );
  AOI211_X1 _182_ (
    .A(tx_state[1]),
    .B(_064_),
    .C1(tx_state[2]),
    .C2(tx_state[3]),
    .ZN(_020_)
  );
  AOI21_X1 _183_ (
    .A(_016_),
    .B1(_089_),
    .B2(tx_state[1]),
    .ZN(_021_)
  );
  OAI21_X1 _184_ (
    .A(_015_),
    .B1(_013_),
    .B2(_086_),
    .ZN(_022_)
  );
  OAI211_X1 _185_ (
    .A(_098_),
    .B(_022_),
    .C1(enable),
    .C2(_094_),
    .ZN(_023_)
  );
  OAI21_X1 _186_ (
    .A(_102_),
    .B1(_020_),
    .B2(_101_),
    .ZN(_024_)
  );
  INV_X1 _187_ (
    .A(_024_),
    .ZN(_025_)
  );
  OAI221_X1 _188_ (
    .A(_109_),
    .B1(_019_),
    .B2(_085_),
    .C1(_021_),
    .C2(enable),
    .ZN(_026_)
  );
  NOR4_X1 _189_ (
    .A1(_088_),
    .A2(_023_),
    .A3(_025_),
    .A4(_026_),
    .ZN(_007_)
  );
  NOR2_X1 _190_ (
    .A1(_101_),
    .A2(_108_),
    .ZN(_027_)
  );
  AND3_X1 _191_ (
    .A1(tx_fifo_out[7]),
    .A2(_094_),
    .A3(_027_),
    .ZN(_001_[7])
  );
  AND2_X1 _192_ (
    .A1(tx_fifo_out[6]),
    .A2(_100_),
    .ZN(_001_[6])
  );
  AND2_X1 _193_ (
    .A1(tx_fifo_out[5]),
    .A2(_094_),
    .ZN(_001_[5])
  );
  XNOR2_X1 _194_ (
    .A(tx_buffer[3]),
    .B(tx_buffer[2]),
    .ZN(_028_)
  );
  XNOR2_X1 _195_ (
    .A(tx_buffer[1]),
    .B(tx_buffer[0]),
    .ZN(_029_)
  );
  XNOR2_X1 _196_ (
    .A(_028_),
    .B(_029_),
    .ZN(_030_)
  );
  XOR2_X1 _197_ (
    .A(tx_buffer[7]),
    .B(tx_buffer[6]),
    .Z(_031_)
  );
  XNOR2_X1 _198_ (
    .A(tx_buffer[5]),
    .B(tx_buffer[4]),
    .ZN(_032_)
  );
  XNOR2_X1 _199_ (
    .A(_031_),
    .B(_032_),
    .ZN(_033_)
  );
  AOI21_X1 _200_ (
    .A(lcr_latched[5]),
    .B1(_030_),
    .B2(_033_),
    .ZN(_034_)
  );
  OAI21_X1 _201_ (
    .A(_034_),
    .B1(_033_),
    .B2(_030_),
    .ZN(_035_)
  );
  XNOR2_X1 _202_ (
    .A(lcr_latched[4]),
    .B(_035_),
    .ZN(_036_)
  );
  AOI22_X1 _203_ (
    .A1(tx_buffer[4]),
    .A2(_093_),
    .B1(_101_),
    .B2(tx_buffer[5]),
    .ZN(_037_)
  );
  NAND2_X1 _204_ (
    .A1(tx_state[0]),
    .A2(_107_),
    .ZN(_038_)
  );
  NAND3_X1 _205_ (
    .A1(tx_state[0]),
    .A2(tx_buffer[7]),
    .A3(_107_),
    .ZN(_039_)
  );
  NAND3_X1 _206_ (
    .A1(_070_),
    .A2(_072_),
    .A3(_080_),
    .ZN(_040_)
  );
  NAND3_X1 _207_ (
    .A1(_018_),
    .A2(_027_),
    .A3(_040_),
    .ZN(_041_)
  );
  AND4_X1 _208_ (
    .A1(tx_state[1]),
    .A2(_064_),
    .A3(tx_buffer[0]),
    .A4(_089_),
    .ZN(_042_)
  );
  NOR3_X1 _209_ (
    .A1(tx_state[1]),
    .A2(_064_),
    .A3(_092_),
    .ZN(_043_)
  );
  AOI221_X1 _210_ (
    .A(_042_),
    .B1(_016_),
    .B2(tx_buffer[2]),
    .C1(tx_buffer[1]),
    .C2(_017_),
    .ZN(_044_)
  );
  AOI22_X1 _211_ (
    .A1(tx_buffer[6]),
    .A2(_108_),
    .B1(_043_),
    .B2(tx_buffer[3]),
    .ZN(_045_)
  );
  AND4_X1 _212_ (
    .A1(_037_),
    .A2(_039_),
    .A3(_044_),
    .A4(_045_),
    .ZN(_046_)
  );
  OAI211_X1 _213_ (
    .A(_041_),
    .B(_046_),
    .C1(_079_),
    .C2(_036_),
    .ZN(_112_)
  );
  AOI21_X1 _214_ (
    .A(_015_),
    .B1(_082_),
    .B2(_074_),
    .ZN(_047_)
  );
  AOI22_X1 _215_ (
    .A1(half_stop_flag),
    .A2(_086_),
    .B1(_013_),
    .B2(_015_),
    .ZN(_048_)
  );
  NOR2_X1 _216_ (
    .A1(_047_),
    .A2(_048_),
    .ZN(_113_)
  );
  NOR2_X1 _217_ (
    .A1(bit_counter[0]),
    .A2(_011_),
    .ZN(_114_[0])
  );
  XNOR2_X1 _218_ (
    .A(bit_counter[1]),
    .B(bit_counter[0]),
    .ZN(_049_)
  );
  NOR2_X1 _219_ (
    .A1(_011_),
    .A2(_049_),
    .ZN(_114_[1])
  );
  AOI21_X1 _220_ (
    .A(bit_counter[2]),
    .B1(bit_counter[0]),
    .B2(bit_counter[1]),
    .ZN(_050_)
  );
  NOR3_X1 _221_ (
    .A1(_084_),
    .A2(_011_),
    .A3(_050_),
    .ZN(_114_[2])
  );
  AOI21_X1 _222_ (
    .A(_015_),
    .B1(_090_),
    .B2(_070_),
    .ZN(_051_)
  );
  NOR2_X1 _223_ (
    .A1(bit_counter[3]),
    .A2(_084_),
    .ZN(_052_)
  );
  NOR3_X1 _224_ (
    .A1(_085_),
    .A2(_051_),
    .A3(_052_),
    .ZN(_114_[3])
  );
  NAND3_X1 _225_ (
    .A1(lcr_latched[0]),
    .A2(_069_),
    .A3(_017_),
    .ZN(_053_)
  );
  OR3_X1 _226_ (
    .A1(tx_state[3]),
    .A2(_080_),
    .A3(_104_),
    .ZN(_054_)
  );
  AOI21_X1 _227_ (
    .A(lcr_latched[3]),
    .B1(_038_),
    .B2(_054_),
    .ZN(_055_)
  );
  AOI221_X1 _228_ (
    .A(_072_),
    .B1(_078_),
    .B2(_092_),
    .C1(_111_),
    .C2(lcr_latched[3]),
    .ZN(_056_)
  );
  AOI211_X1 _229_ (
    .A(tx_state[3]),
    .B(_075_),
    .C1(_095_),
    .C2(lcr_latched[3]),
    .ZN(_057_)
  );
  NAND2_X1 _230_ (
    .A1(_079_),
    .A2(_090_),
    .ZN(_058_)
  );
  OR4_X1 _231_ (
    .A1(_055_),
    .A2(_056_),
    .A3(_057_),
    .A4(_058_),
    .ZN(_115_[0])
  );
  NAND2_X1 _232_ (
    .A1(_111_),
    .A2(_016_),
    .ZN(_059_)
  );
  NAND4_X1 _233_ (
    .A1(_009_),
    .A2(_040_),
    .A3(_054_),
    .A4(_059_),
    .ZN(_115_[1])
  );
  AOI21_X1 _234_ (
    .A(_043_),
    .B1(_081_),
    .B2(lcr_latched[2]),
    .ZN(_060_)
  );
  NOR3_X1 _235_ (
    .A1(_072_),
    .A2(_092_),
    .A3(_111_),
    .ZN(_061_)
  );
  AOI21_X1 _236_ (
    .A(_061_),
    .B1(_017_),
    .B2(_104_),
    .ZN(_062_)
  );
  NAND3_X1 _237_ (
    .A1(_096_),
    .A2(_060_),
    .A3(_062_),
    .ZN(_115_[2])
  );
  AOI211_X1 _238_ (
    .A(_101_),
    .B(_107_),
    .C1(_091_),
    .C2(_095_),
    .ZN(_063_)
  );
  NAND4_X1 _239_ (
    .A1(_083_),
    .A2(_053_),
    .A3(_059_),
    .A4(_063_),
    .ZN(_115_[3])
  );
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) tx_buffer[7] <= 1'h0;
    else if (_003_) tx_buffer[7] <= _001_[7];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) tx_buffer[6] <= 1'h0;
    else if (_004_) tx_buffer[6] <= _001_[6];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) tx_buffer[5] <= 1'h0;
    else if (_005_) tx_buffer[5] <= _001_[5];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) half_stop_flag <= 1'h0;
    else if (_002_) half_stop_flag <= _113_;
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) TXD <= 1'h1;
    else TXD <= _112_;
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) busy <= 1'h0;
    else if (!_008_) busy <= _000_;
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) tx_state[0] <= 1'h0;
    else if (_007_) tx_state[0] <= _115_[0];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) tx_state[1] <= 1'h0;
    else if (_007_) tx_state[1] <= _115_[1];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) tx_state[2] <= 1'h0;
    else if (_007_) tx_state[2] <= _115_[2];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) tx_state[3] <= 1'h0;
    else if (_007_) tx_state[3] <= _115_[3];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) bit_counter[0] <= 1'h0;
    else if (_006_) bit_counter[0] <= _114_[0];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) bit_counter[1] <= 1'h0;
    else if (_006_) bit_counter[1] <= _114_[1];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) bit_counter[2] <= 1'h0;
    else if (_006_) bit_counter[2] <= _114_[2];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) bit_counter[3] <= 1'h0;
    else if (_006_) bit_counter[3] <= _114_[3];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) pop_tx_fifo <= 1'h0;
    else pop_tx_fifo <= _000_;
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) tx_buffer[0] <= 1'h0;
    else if (_000_) tx_buffer[0] <= tx_fifo_out[0];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) tx_buffer[1] <= 1'h0;
    else if (_000_) tx_buffer[1] <= tx_fifo_out[1];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) tx_buffer[2] <= 1'h0;
    else if (_000_) tx_buffer[2] <= tx_fifo_out[2];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) tx_buffer[3] <= 1'h0;
    else if (_000_) tx_buffer[3] <= tx_fifo_out[3];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) tx_buffer[4] <= 1'h0;
    else if (_000_) tx_buffer[4] <= tx_fifo_out[4];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) lcr_latched[0] <= 1'h0;
    else if (_000_) lcr_latched[0] <= LCR[0];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) lcr_latched[1] <= 1'h0;
    else if (_000_) lcr_latched[1] <= LCR[1];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) lcr_latched[2] <= 1'h0;
    else if (_000_) lcr_latched[2] <= LCR[2];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) lcr_latched[3] <= 1'h0;
    else if (_000_) lcr_latched[3] <= LCR[3];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) lcr_latched[4] <= 1'h0;
    else if (_000_) lcr_latched[4] <= LCR[4];
  (* src = "uart_tx_combined.v:137.5-361.8" *)
  always @(posedge PCLK, negedge PRESETn)
    if (!PRESETn) lcr_latched[5] <= 1'h0;
    else if (_000_) lcr_latched[5] <= LCR[5];
  (* module_not_derived = 32'd1 *)
  (* src = "uart_tx_combined.v:121.18-131.6" *)
  uart_tx_fifo u_fifo (
    .clk(PCLK),
    .count_out(tx_fifo_count_w),
    .pop(pop_tx_fifo),
    .push(tx_fifo_push),
    .rd_data(tx_fifo_out),
    .rst_n(PRESETn),
    .tx_fifo_empty(tx_fifo_empty_w),
    .tx_fifo_full(tx_fifo_full_w),
    .wr_data(PWDATA)
  );
  assign tx_fifo_count = tx_fifo_count_w;
  assign tx_fifo_empty = tx_fifo_empty_w;
  assign tx_fifo_full = tx_fifo_full_w;
endmodule

(* dynports =  1  *)
(* src = "uart_tx_combined.v:10.1-75.10" *)
module uart_tx_fifo(clk, rst_n, push, wr_data, tx_fifo_full, pop, rd_data, tx_fifo_empty, count_out);
  (* src = "uart_tx_combined.v:11.24-11.27" *)
  input clk;
  wire clk;
  (* src = "uart_tx_combined.v:12.24-12.29" *)
  input rst_n;
  wire rst_n;
  (* src = "uart_tx_combined.v:13.24-13.28" *)
  input push;
  wire push;
  (* src = "uart_tx_combined.v:14.24-14.31" *)
  input [7:0] wr_data;
  wire [7:0] wr_data;
  (* src = "uart_tx_combined.v:15.24-15.36" *)
  output tx_fifo_full;
  wire tx_fifo_full;
  (* src = "uart_tx_combined.v:16.24-16.27" *)
  input pop;
  wire pop;
  (* src = "uart_tx_combined.v:17.24-17.31" *)
  output [7:0] rd_data;
  wire [7:0] rd_data;
  (* src = "uart_tx_combined.v:18.24-18.37" *)
  output tx_fifo_empty;
  wire tx_fifo_empty;
  (* src = "uart_tx_combined.v:19.24-19.33" *)
  output [4:0] count_out;
  wire [4:0] count_out;
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  wire [4:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  (* force_downto = 32'd1 *)
  (* src = "uart_tx_combined.v:48.29-48.44|/opt/oss-cad-suite/lib/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _135_;
  (* force_downto = 32'd1 *)
  (* src = "uart_tx_combined.v:48.29-48.44|/opt/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _136_;
  (* force_downto = 32'd1 *)
  (* src = "uart_tx_combined.v:52.29-52.44|/opt/oss-cad-suite/lib/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _137_;
  (* force_downto = 32'd1 *)
  (* src = "uart_tx_combined.v:52.29-52.44|/opt/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _138_;
  (* src = "uart_tx_combined.v:29.26-29.31" *)
  reg [4:0] count;
  (* src = "uart_tx_combined.v:26.26-26.35" *)
  reg [7:0] \data_fifo[0] ;
  (* src = "uart_tx_combined.v:26.26-26.35" *)
  reg [7:0] \data_fifo[10] ;
  (* src = "uart_tx_combined.v:26.26-26.35" *)
  reg [7:0] \data_fifo[11] ;
  (* src = "uart_tx_combined.v:26.26-26.35" *)
  reg [7:0] \data_fifo[12] ;
  (* src = "uart_tx_combined.v:26.26-26.35" *)
  reg [7:0] \data_fifo[13] ;
  (* src = "uart_tx_combined.v:26.26-26.35" *)
  reg [7:0] \data_fifo[14] ;
  (* src = "uart_tx_combined.v:26.26-26.35" *)
  reg [7:0] \data_fifo[15] ;
  (* src = "uart_tx_combined.v:26.26-26.35" *)
  reg [7:0] \data_fifo[1] ;
  (* src = "uart_tx_combined.v:26.26-26.35" *)
  reg [7:0] \data_fifo[2] ;
  (* src = "uart_tx_combined.v:26.26-26.35" *)
  reg [7:0] \data_fifo[3] ;
  (* src = "uart_tx_combined.v:26.26-26.35" *)
  reg [7:0] \data_fifo[4] ;
  (* src = "uart_tx_combined.v:26.26-26.35" *)
  reg [7:0] \data_fifo[5] ;
  (* src = "uart_tx_combined.v:26.26-26.35" *)
  reg [7:0] \data_fifo[6] ;
  (* src = "uart_tx_combined.v:26.26-26.35" *)
  reg [7:0] \data_fifo[7] ;
  (* src = "uart_tx_combined.v:26.26-26.35" *)
  reg [7:0] \data_fifo[8] ;
  (* src = "uart_tx_combined.v:26.26-26.35" *)
  reg [7:0] \data_fifo[9] ;
  (* src = "uart_tx_combined.v:27.26-27.34" *)
  reg [3:0] ip_count;
  (* src = "uart_tx_combined.v:28.26-28.34" *)
  reg [3:0] op_count;
  INV_X1 _139_ (
    .A(ip_count[0]),
    .ZN(_135_[0])
  );
  INV_X1 _140_ (
    .A(op_count[0]),
    .ZN(_137_[0])
  );
  INV_X1 _141_ (
    .A(push),
    .ZN(_020_)
  );
  INV_X1 _142_ (
    .A(pop),
    .ZN(_021_)
  );
  INV_X1 _143_ (
    .A(count[0]),
    .ZN(_000_[0])
  );
  INV_X1 _144_ (
    .A(count[2]),
    .ZN(_022_)
  );
  INV_X1 _145_ (
    .A(count[4]),
    .ZN(_023_)
  );
  INV_X1 _146_ (
    .A(ip_count[1]),
    .ZN(_024_)
  );
  INV_X1 _147_ (
    .A(ip_count[2]),
    .ZN(_025_)
  );
  INV_X1 _148_ (
    .A(op_count[2]),
    .ZN(_026_)
  );
  INV_X1 _149_ (
    .A(op_count[3]),
    .ZN(_027_)
  );
  INV_X1 _150_ (
    .A(op_count[1]),
    .ZN(_028_)
  );
  NOR2_X1 _151_ (
    .A1(count[0]),
    .A2(count[1]),
    .ZN(_029_)
  );
  NOR3_X1 _152_ (
    .A1(count[0]),
    .A2(count[1]),
    .A3(count[2]),
    .ZN(_030_)
  );
  OR4_X1 _153_ (
    .A1(count[0]),
    .A2(count[1]),
    .A3(count[2]),
    .A4(count[3]),
    .ZN(_031_)
  );
  NOR2_X1 _154_ (
    .A1(_023_),
    .A2(_031_),
    .ZN(tx_fifo_full)
  );
  NOR2_X1 _155_ (
    .A1(count[4]),
    .A2(_031_),
    .ZN(tx_fifo_empty)
  );
  NOR2_X1 _156_ (
    .A1(_021_),
    .A2(tx_fifo_empty),
    .ZN(_003_)
  );
  NOR3_X1 _157_ (
    .A1(push),
    .A2(_021_),
    .A3(tx_fifo_empty),
    .ZN(_032_)
  );
  OAI211_X1 _158_ (
    .A(_020_),
    .B(pop),
    .C1(count[4]),
    .C2(_031_),
    .ZN(_033_)
  );
  OR3_X1 _159_ (
    .A1(ip_count[2]),
    .A2(ip_count[3]),
    .A3(_032_),
    .ZN(_034_)
  );
  OAI21_X1 _160_ (
    .A(push),
    .B1(_023_),
    .B2(_031_),
    .ZN(_035_)
  );
  AOI21_X1 _161_ (
    .A(_020_),
    .B1(_021_),
    .B2(tx_fifo_full),
    .ZN(_001_)
  );
  NAND3_X1 _162_ (
    .A1(_135_[0]),
    .A2(_024_),
    .A3(_001_),
    .ZN(_036_)
  );
  NOR2_X1 _163_ (
    .A1(_034_),
    .A2(_036_),
    .ZN(_004_)
  );
  NAND3_X1 _164_ (
    .A1(ip_count[0]),
    .A2(_024_),
    .A3(_001_),
    .ZN(_037_)
  );
  NOR2_X1 _165_ (
    .A1(_034_),
    .A2(_037_),
    .ZN(_005_)
  );
  NAND3_X1 _166_ (
    .A1(_135_[0]),
    .A2(ip_count[1]),
    .A3(_001_),
    .ZN(_038_)
  );
  NOR2_X1 _167_ (
    .A1(_034_),
    .A2(_038_),
    .ZN(_006_)
  );
  NAND2_X1 _168_ (
    .A1(ip_count[0]),
    .A2(ip_count[1]),
    .ZN(_039_)
  );
  NAND3_X1 _169_ (
    .A1(ip_count[0]),
    .A2(ip_count[1]),
    .A3(_001_),
    .ZN(_040_)
  );
  NOR2_X1 _170_ (
    .A1(_034_),
    .A2(_040_),
    .ZN(_007_)
  );
  OR3_X1 _171_ (
    .A1(_025_),
    .A2(ip_count[3]),
    .A3(_032_),
    .ZN(_041_)
  );
  NOR2_X1 _172_ (
    .A1(_036_),
    .A2(_041_),
    .ZN(_008_)
  );
  NOR2_X1 _173_ (
    .A1(_037_),
    .A2(_041_),
    .ZN(_009_)
  );
  NOR2_X1 _174_ (
    .A1(_038_),
    .A2(_041_),
    .ZN(_010_)
  );
  NOR2_X1 _175_ (
    .A1(_040_),
    .A2(_041_),
    .ZN(_011_)
  );
  NAND3_X1 _176_ (
    .A1(_025_),
    .A2(ip_count[3]),
    .A3(_033_),
    .ZN(_042_)
  );
  NOR2_X1 _177_ (
    .A1(_036_),
    .A2(_042_),
    .ZN(_012_)
  );
  NOR2_X1 _178_ (
    .A1(_037_),
    .A2(_042_),
    .ZN(_013_)
  );
  NOR2_X1 _179_ (
    .A1(_038_),
    .A2(_042_),
    .ZN(_014_)
  );
  NOR2_X1 _180_ (
    .A1(_040_),
    .A2(_042_),
    .ZN(_015_)
  );
  NAND3_X1 _181_ (
    .A1(ip_count[2]),
    .A2(ip_count[3]),
    .A3(_033_),
    .ZN(_043_)
  );
  NOR2_X1 _182_ (
    .A1(_036_),
    .A2(_043_),
    .ZN(_016_)
  );
  NOR2_X1 _183_ (
    .A1(_037_),
    .A2(_043_),
    .ZN(_017_)
  );
  NOR2_X1 _184_ (
    .A1(_038_),
    .A2(_043_),
    .ZN(_018_)
  );
  NOR2_X1 _185_ (
    .A1(_040_),
    .A2(_043_),
    .ZN(_019_)
  );
  OAI21_X1 _186_ (
    .A(_033_),
    .B1(_035_),
    .B2(_003_),
    .ZN(_002_)
  );
  NAND2_X1 _187_ (
    .A1(count[0]),
    .A2(count[1]),
    .ZN(_044_)
  );
  XOR2_X1 _188_ (
    .A(count[0]),
    .B(count[1]),
    .Z(_045_)
  );
  XNOR2_X1 _189_ (
    .A(_033_),
    .B(_045_),
    .ZN(_000_[1])
  );
  NAND2_X1 _190_ (
    .A1(_033_),
    .A2(_044_),
    .ZN(_046_)
  );
  OAI21_X1 _191_ (
    .A(_046_),
    .B1(_033_),
    .B2(_029_),
    .ZN(_047_)
  );
  XNOR2_X1 _192_ (
    .A(count[2]),
    .B(_047_),
    .ZN(_000_[2])
  );
  OAI21_X1 _193_ (
    .A(_033_),
    .B1(_044_),
    .B2(_022_),
    .ZN(_048_)
  );
  OAI21_X1 _194_ (
    .A(_048_),
    .B1(_033_),
    .B2(_030_),
    .ZN(_049_)
  );
  XNOR2_X1 _195_ (
    .A(count[3]),
    .B(_049_),
    .ZN(_000_[3])
  );
  NAND4_X1 _196_ (
    .A1(_020_),
    .A2(pop),
    .A3(count[4]),
    .A4(_031_),
    .ZN(_050_)
  );
  NAND4_X1 _197_ (
    .A1(count[0]),
    .A2(count[1]),
    .A3(count[2]),
    .A4(count[3]),
    .ZN(_051_)
  );
  XNOR2_X1 _198_ (
    .A(_023_),
    .B(_051_),
    .ZN(_052_)
  );
  OAI21_X1 _199_ (
    .A(_050_),
    .B1(_052_),
    .B2(_032_),
    .ZN(_000_[4])
  );
  NAND2_X1 _200_ (
    .A1(op_count[0]),
    .A2(op_count[1]),
    .ZN(_053_)
  );
  NAND3_X1 _201_ (
    .A1(op_count[0]),
    .A2(op_count[2]),
    .A3(op_count[1]),
    .ZN(_054_)
  );
  NOR2_X1 _202_ (
    .A1(op_count[3]),
    .A2(_054_),
    .ZN(_055_)
  );
  NOR4_X1 _203_ (
    .A1(op_count[0]),
    .A2(op_count[2]),
    .A3(op_count[3]),
    .A4(_028_),
    .ZN(_056_)
  );
  AOI22_X1 _204_ (
    .A1(\data_fifo[7] [0]),
    .A2(_055_),
    .B1(_056_),
    .B2(\data_fifo[2] [0]),
    .ZN(_057_)
  );
  NAND2_X1 _205_ (
    .A1(op_count[2]),
    .A2(op_count[3]),
    .ZN(_058_)
  );
  NOR3_X1 _206_ (
    .A1(op_count[0]),
    .A2(op_count[1]),
    .A3(_058_),
    .ZN(_059_)
  );
  NOR3_X1 _207_ (
    .A1(_137_[0]),
    .A2(op_count[1]),
    .A3(_058_),
    .ZN(_060_)
  );
  AOI22_X1 _208_ (
    .A1(\data_fifo[12] [0]),
    .A2(_059_),
    .B1(_060_),
    .B2(\data_fifo[13] [0]),
    .ZN(_061_)
  );
  NOR4_X1 _209_ (
    .A1(op_count[0]),
    .A2(op_count[2]),
    .A3(op_count[3]),
    .A4(op_count[1]),
    .ZN(_062_)
  );
  NOR3_X1 _210_ (
    .A1(op_count[2]),
    .A2(op_count[3]),
    .A3(_053_),
    .ZN(_063_)
  );
  AOI22_X1 _211_ (
    .A1(\data_fifo[0] [0]),
    .A2(_062_),
    .B1(_063_),
    .B2(\data_fifo[3] [0]),
    .ZN(_064_)
  );
  NOR2_X1 _212_ (
    .A1(_027_),
    .A2(_054_),
    .ZN(_065_)
  );
  NOR4_X1 _213_ (
    .A1(_137_[0]),
    .A2(op_count[2]),
    .A3(_027_),
    .A4(op_count[1]),
    .ZN(_066_)
  );
  AOI22_X1 _214_ (
    .A1(\data_fifo[15] [0]),
    .A2(_065_),
    .B1(_066_),
    .B2(\data_fifo[9] [0]),
    .ZN(_067_)
  );
  NAND4_X1 _215_ (
    .A1(_057_),
    .A2(_061_),
    .A3(_064_),
    .A4(_067_),
    .ZN(_068_)
  );
  NOR4_X1 _216_ (
    .A1(op_count[0]),
    .A2(op_count[2]),
    .A3(_027_),
    .A4(_028_),
    .ZN(_069_)
  );
  NOR4_X1 _217_ (
    .A1(op_count[0]),
    .A2(_026_),
    .A3(op_count[3]),
    .A4(_028_),
    .ZN(_070_)
  );
  AOI22_X1 _218_ (
    .A1(\data_fifo[10] [0]),
    .A2(_069_),
    .B1(_070_),
    .B2(\data_fifo[6] [0]),
    .ZN(_071_)
  );
  NOR4_X1 _219_ (
    .A1(op_count[0]),
    .A2(op_count[2]),
    .A3(_027_),
    .A4(op_count[1]),
    .ZN(_072_)
  );
  NOR3_X1 _220_ (
    .A1(op_count[0]),
    .A2(_028_),
    .A3(_058_),
    .ZN(_073_)
  );
  AOI22_X1 _221_ (
    .A1(\data_fifo[8] [0]),
    .A2(_072_),
    .B1(_073_),
    .B2(\data_fifo[14] [0]),
    .ZN(_074_)
  );
  NOR4_X1 _222_ (
    .A1(op_count[0]),
    .A2(_026_),
    .A3(op_count[3]),
    .A4(op_count[1]),
    .ZN(_075_)
  );
  NOR4_X1 _223_ (
    .A1(_137_[0]),
    .A2(_026_),
    .A3(op_count[3]),
    .A4(op_count[1]),
    .ZN(_076_)
  );
  AOI22_X1 _224_ (
    .A1(\data_fifo[4] [0]),
    .A2(_075_),
    .B1(_076_),
    .B2(\data_fifo[5] [0]),
    .ZN(_077_)
  );
  NOR3_X1 _225_ (
    .A1(op_count[2]),
    .A2(_027_),
    .A3(_053_),
    .ZN(_078_)
  );
  NOR4_X1 _226_ (
    .A1(_137_[0]),
    .A2(op_count[2]),
    .A3(op_count[3]),
    .A4(op_count[1]),
    .ZN(_079_)
  );
  AOI22_X1 _227_ (
    .A1(\data_fifo[11] [0]),
    .A2(_078_),
    .B1(_079_),
    .B2(\data_fifo[1] [0]),
    .ZN(_080_)
  );
  NAND4_X1 _228_ (
    .A1(_071_),
    .A2(_074_),
    .A3(_077_),
    .A4(_080_),
    .ZN(_081_)
  );
  OR2_X1 _229_ (
    .A1(_068_),
    .A2(_081_),
    .ZN(rd_data[0])
  );
  AOI22_X1 _230_ (
    .A1(\data_fifo[3] [1]),
    .A2(_063_),
    .B1(_069_),
    .B2(\data_fifo[10] [1]),
    .ZN(_082_)
  );
  AOI222_X1 _231_ (
    .A1(\data_fifo[12] [1]),
    .A2(_059_),
    .B1(_078_),
    .B2(\data_fifo[11] [1]),
    .C1(_060_),
    .C2(\data_fifo[13] [1]),
    .ZN(_083_)
  );
  AOI222_X1 _232_ (
    .A1(\data_fifo[7] [1]),
    .A2(_055_),
    .B1(_056_),
    .B2(\data_fifo[2] [1]),
    .C1(_072_),
    .C2(\data_fifo[8] [1]),
    .ZN(_084_)
  );
  AOI222_X1 _233_ (
    .A1(\data_fifo[15] [1]),
    .A2(_065_),
    .B1(_075_),
    .B2(\data_fifo[4] [1]),
    .C1(_079_),
    .C2(\data_fifo[1] [1]),
    .ZN(_085_)
  );
  AOI222_X1 _234_ (
    .A1(\data_fifo[9] [1]),
    .A2(_066_),
    .B1(_070_),
    .B2(\data_fifo[6] [1]),
    .C1(_076_),
    .C2(\data_fifo[5] [1]),
    .ZN(_086_)
  );
  AOI22_X1 _235_ (
    .A1(\data_fifo[0] [1]),
    .A2(_062_),
    .B1(_073_),
    .B2(\data_fifo[14] [1]),
    .ZN(_087_)
  );
  AND4_X1 _236_ (
    .A1(_084_),
    .A2(_085_),
    .A3(_086_),
    .A4(_087_),
    .ZN(_088_)
  );
  NAND3_X1 _237_ (
    .A1(_082_),
    .A2(_083_),
    .A3(_088_),
    .ZN(rd_data[1])
  );
  AOI222_X1 _238_ (
    .A1(\data_fifo[12] [2]),
    .A2(_059_),
    .B1(_069_),
    .B2(\data_fifo[10] [2]),
    .C1(_078_),
    .C2(\data_fifo[11] [2]),
    .ZN(_089_)
  );
  AOI22_X1 _239_ (
    .A1(\data_fifo[0] [2]),
    .A2(_062_),
    .B1(_066_),
    .B2(\data_fifo[9] [2]),
    .ZN(_090_)
  );
  AOI22_X1 _240_ (
    .A1(\data_fifo[2] [2]),
    .A2(_056_),
    .B1(_073_),
    .B2(\data_fifo[14] [2]),
    .ZN(_091_)
  );
  AOI222_X1 _241_ (
    .A1(\data_fifo[6] [2]),
    .A2(_070_),
    .B1(_076_),
    .B2(\data_fifo[5] [2]),
    .C1(_072_),
    .C2(\data_fifo[8] [2]),
    .ZN(_092_)
  );
  AOI222_X1 _242_ (
    .A1(\data_fifo[7] [2]),
    .A2(_055_),
    .B1(_060_),
    .B2(\data_fifo[13] [2]),
    .C1(\data_fifo[15] [2]),
    .C2(_065_),
    .ZN(_093_)
  );
  AOI222_X1 _243_ (
    .A1(\data_fifo[3] [2]),
    .A2(_063_),
    .B1(_079_),
    .B2(\data_fifo[1] [2]),
    .C1(_075_),
    .C2(\data_fifo[4] [2]),
    .ZN(_094_)
  );
  AND3_X1 _244_ (
    .A1(_092_),
    .A2(_093_),
    .A3(_094_),
    .ZN(_095_)
  );
  NAND4_X1 _245_ (
    .A1(_089_),
    .A2(_090_),
    .A3(_091_),
    .A4(_095_),
    .ZN(rd_data[2])
  );
  AOI22_X1 _246_ (
    .A1(\data_fifo[15] [3]),
    .A2(_065_),
    .B1(_072_),
    .B2(\data_fifo[8] [3]),
    .ZN(_096_)
  );
  AOI22_X1 _247_ (
    .A1(\data_fifo[7] [3]),
    .A2(_055_),
    .B1(_078_),
    .B2(\data_fifo[11] [3]),
    .ZN(_097_)
  );
  NAND2_X1 _248_ (
    .A1(\data_fifo[12] [3]),
    .A2(_059_),
    .ZN(_098_)
  );
  AOI222_X1 _249_ (
    .A1(\data_fifo[2] [3]),
    .A2(_056_),
    .B1(_079_),
    .B2(\data_fifo[1] [3]),
    .C1(_076_),
    .C2(\data_fifo[5] [3]),
    .ZN(_099_)
  );
  AOI22_X1 _250_ (
    .A1(\data_fifo[0] [3]),
    .A2(_062_),
    .B1(_075_),
    .B2(\data_fifo[4] [3]),
    .ZN(_100_)
  );
  AND4_X1 _251_ (
    .A1(_096_),
    .A2(_097_),
    .A3(_099_),
    .A4(_100_),
    .ZN(_101_)
  );
  AOI222_X1 _252_ (
    .A1(\data_fifo[13] [3]),
    .A2(_060_),
    .B1(_063_),
    .B2(\data_fifo[3] [3]),
    .C1(_069_),
    .C2(\data_fifo[10] [3]),
    .ZN(_102_)
  );
  AOI222_X1 _253_ (
    .A1(\data_fifo[9] [3]),
    .A2(_066_),
    .B1(_070_),
    .B2(\data_fifo[6] [3]),
    .C1(_073_),
    .C2(\data_fifo[14] [3]),
    .ZN(_103_)
  );
  NAND4_X1 _254_ (
    .A1(_098_),
    .A2(_101_),
    .A3(_102_),
    .A4(_103_),
    .ZN(rd_data[3])
  );
  AOI222_X1 _255_ (
    .A1(\data_fifo[12] [4]),
    .A2(_059_),
    .B1(_069_),
    .B2(\data_fifo[10] [4]),
    .C1(_078_),
    .C2(\data_fifo[11] [4]),
    .ZN(_104_)
  );
  AOI22_X1 _256_ (
    .A1(\data_fifo[0] [4]),
    .A2(_062_),
    .B1(_066_),
    .B2(\data_fifo[9] [4]),
    .ZN(_105_)
  );
  AOI22_X1 _257_ (
    .A1(\data_fifo[2] [4]),
    .A2(_056_),
    .B1(_073_),
    .B2(\data_fifo[14] [4]),
    .ZN(_106_)
  );
  NAND3_X1 _258_ (
    .A1(_104_),
    .A2(_105_),
    .A3(_106_),
    .ZN(_107_)
  );
  AOI222_X1 _259_ (
    .A1(\data_fifo[6] [4]),
    .A2(_070_),
    .B1(_076_),
    .B2(\data_fifo[5] [4]),
    .C1(_072_),
    .C2(\data_fifo[8] [4]),
    .ZN(_108_)
  );
  AOI222_X1 _260_ (
    .A1(\data_fifo[7] [4]),
    .A2(_055_),
    .B1(_060_),
    .B2(\data_fifo[13] [4]),
    .C1(\data_fifo[15] [4]),
    .C2(_065_),
    .ZN(_109_)
  );
  AOI222_X1 _261_ (
    .A1(\data_fifo[3] [4]),
    .A2(_063_),
    .B1(_079_),
    .B2(\data_fifo[1] [4]),
    .C1(_075_),
    .C2(\data_fifo[4] [4]),
    .ZN(_110_)
  );
  NAND3_X1 _262_ (
    .A1(_108_),
    .A2(_109_),
    .A3(_110_),
    .ZN(_111_)
  );
  OR2_X1 _263_ (
    .A1(_107_),
    .A2(_111_),
    .ZN(rd_data[4])
  );
  AOI22_X1 _264_ (
    .A1(\data_fifo[3] [5]),
    .A2(_063_),
    .B1(_069_),
    .B2(\data_fifo[10] [5]),
    .ZN(_112_)
  );
  AOI222_X1 _265_ (
    .A1(\data_fifo[12] [5]),
    .A2(_059_),
    .B1(_078_),
    .B2(\data_fifo[11] [5]),
    .C1(_060_),
    .C2(\data_fifo[13] [5]),
    .ZN(_113_)
  );
  AOI222_X1 _266_ (
    .A1(\data_fifo[7] [5]),
    .A2(_055_),
    .B1(_056_),
    .B2(\data_fifo[2] [5]),
    .C1(_072_),
    .C2(\data_fifo[8] [5]),
    .ZN(_114_)
  );
  AOI222_X1 _267_ (
    .A1(\data_fifo[15] [5]),
    .A2(_065_),
    .B1(_075_),
    .B2(\data_fifo[4] [5]),
    .C1(_079_),
    .C2(\data_fifo[1] [5]),
    .ZN(_115_)
  );
  AOI222_X1 _268_ (
    .A1(\data_fifo[9] [5]),
    .A2(_066_),
    .B1(_070_),
    .B2(\data_fifo[6] [5]),
    .C1(_076_),
    .C2(\data_fifo[5] [5]),
    .ZN(_116_)
  );
  AOI22_X1 _269_ (
    .A1(\data_fifo[0] [5]),
    .A2(_062_),
    .B1(_073_),
    .B2(\data_fifo[14] [5]),
    .ZN(_117_)
  );
  AND4_X1 _270_ (
    .A1(_114_),
    .A2(_115_),
    .A3(_116_),
    .A4(_117_),
    .ZN(_118_)
  );
  NAND3_X1 _271_ (
    .A1(_112_),
    .A2(_113_),
    .A3(_118_),
    .ZN(rd_data[5])
  );
  AOI222_X1 _272_ (
    .A1(\data_fifo[12] [6]),
    .A2(_059_),
    .B1(_069_),
    .B2(\data_fifo[10] [6]),
    .C1(_078_),
    .C2(\data_fifo[11] [6]),
    .ZN(_119_)
  );
  AOI22_X1 _273_ (
    .A1(\data_fifo[0] [6]),
    .A2(_062_),
    .B1(_066_),
    .B2(\data_fifo[9] [6]),
    .ZN(_120_)
  );
  AOI22_X1 _274_ (
    .A1(\data_fifo[2] [6]),
    .A2(_056_),
    .B1(_073_),
    .B2(\data_fifo[14] [6]),
    .ZN(_121_)
  );
  NAND3_X1 _275_ (
    .A1(_119_),
    .A2(_120_),
    .A3(_121_),
    .ZN(_122_)
  );
  AOI222_X1 _276_ (
    .A1(\data_fifo[6] [6]),
    .A2(_070_),
    .B1(_076_),
    .B2(\data_fifo[5] [6]),
    .C1(_072_),
    .C2(\data_fifo[8] [6]),
    .ZN(_123_)
  );
  AOI222_X1 _277_ (
    .A1(\data_fifo[7] [6]),
    .A2(_055_),
    .B1(_060_),
    .B2(\data_fifo[13] [6]),
    .C1(\data_fifo[15] [6]),
    .C2(_065_),
    .ZN(_124_)
  );
  AOI222_X1 _278_ (
    .A1(\data_fifo[3] [6]),
    .A2(_063_),
    .B1(_079_),
    .B2(\data_fifo[1] [6]),
    .C1(_075_),
    .C2(\data_fifo[4] [6]),
    .ZN(_125_)
  );
  NAND3_X1 _279_ (
    .A1(_123_),
    .A2(_124_),
    .A3(_125_),
    .ZN(_126_)
  );
  OR2_X1 _280_ (
    .A1(_122_),
    .A2(_126_),
    .ZN(rd_data[6])
  );
  AOI222_X1 _281_ (
    .A1(\data_fifo[12] [7]),
    .A2(_059_),
    .B1(_069_),
    .B2(\data_fifo[10] [7]),
    .C1(_078_),
    .C2(\data_fifo[11] [7]),
    .ZN(_127_)
  );
  AOI22_X1 _282_ (
    .A1(\data_fifo[0] [7]),
    .A2(_062_),
    .B1(_066_),
    .B2(\data_fifo[9] [7]),
    .ZN(_128_)
  );
  AOI22_X1 _283_ (
    .A1(\data_fifo[2] [7]),
    .A2(_056_),
    .B1(_073_),
    .B2(\data_fifo[14] [7]),
    .ZN(_129_)
  );
  AOI222_X1 _284_ (
    .A1(\data_fifo[6] [7]),
    .A2(_070_),
    .B1(_076_),
    .B2(\data_fifo[5] [7]),
    .C1(_072_),
    .C2(\data_fifo[8] [7]),
    .ZN(_130_)
  );
  AOI222_X1 _285_ (
    .A1(\data_fifo[7] [7]),
    .A2(_055_),
    .B1(_060_),
    .B2(\data_fifo[13] [7]),
    .C1(\data_fifo[15] [7]),
    .C2(_065_),
    .ZN(_131_)
  );
  AOI222_X1 _286_ (
    .A1(\data_fifo[3] [7]),
    .A2(_063_),
    .B1(_079_),
    .B2(\data_fifo[1] [7]),
    .C1(_075_),
    .C2(\data_fifo[4] [7]),
    .ZN(_132_)
  );
  AND3_X1 _287_ (
    .A1(_130_),
    .A2(_131_),
    .A3(_132_),
    .ZN(_133_)
  );
  NAND4_X1 _288_ (
    .A1(_127_),
    .A2(_128_),
    .A3(_129_),
    .A4(_133_),
    .ZN(rd_data[7])
  );
  XOR2_X1 _289_ (
    .A(ip_count[0]),
    .B(ip_count[1]),
    .Z(_136_[1])
  );
  NAND3_X1 _290_ (
    .A1(ip_count[0]),
    .A2(ip_count[1]),
    .A3(ip_count[2]),
    .ZN(_134_)
  );
  XNOR2_X1 _291_ (
    .A(ip_count[2]),
    .B(_039_),
    .ZN(_136_[2])
  );
  XNOR2_X1 _292_ (
    .A(ip_count[3]),
    .B(_134_),
    .ZN(_136_[3])
  );
  XOR2_X1 _293_ (
    .A(op_count[0]),
    .B(op_count[1]),
    .Z(_138_[1])
  );
  XNOR2_X1 _294_ (
    .A(op_count[2]),
    .B(_053_),
    .ZN(_138_[2])
  );
  XNOR2_X1 _295_ (
    .A(op_count[3]),
    .B(_054_),
    .ZN(_138_[3])
  );
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[0] [0] <= 1'h0;
    else if (_004_) \data_fifo[0] [0] <= wr_data[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[0] [1] <= 1'h0;
    else if (_004_) \data_fifo[0] [1] <= wr_data[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[0] [2] <= 1'h0;
    else if (_004_) \data_fifo[0] [2] <= wr_data[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[0] [3] <= 1'h0;
    else if (_004_) \data_fifo[0] [3] <= wr_data[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[0] [4] <= 1'h0;
    else if (_004_) \data_fifo[0] [4] <= wr_data[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[0] [5] <= 1'h0;
    else if (_004_) \data_fifo[0] [5] <= wr_data[5];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[0] [6] <= 1'h0;
    else if (_004_) \data_fifo[0] [6] <= wr_data[6];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[0] [7] <= 1'h0;
    else if (_004_) \data_fifo[0] [7] <= wr_data[7];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ip_count[0] <= 1'h0;
    else if (_001_) ip_count[0] <= _135_[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ip_count[1] <= 1'h0;
    else if (_001_) ip_count[1] <= _136_[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ip_count[2] <= 1'h0;
    else if (_001_) ip_count[2] <= _136_[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ip_count[3] <= 1'h0;
    else if (_001_) ip_count[3] <= _136_[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) op_count[0] <= 1'h0;
    else if (_003_) op_count[0] <= _137_[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) op_count[1] <= 1'h0;
    else if (_003_) op_count[1] <= _138_[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) op_count[2] <= 1'h0;
    else if (_003_) op_count[2] <= _138_[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) op_count[3] <= 1'h0;
    else if (_003_) op_count[3] <= _138_[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[0] <= 1'h0;
    else if (_002_) count[0] <= _000_[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[1] <= 1'h0;
    else if (_002_) count[1] <= _000_[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[2] <= 1'h0;
    else if (_002_) count[2] <= _000_[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[3] <= 1'h0;
    else if (_002_) count[3] <= _000_[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) count[4] <= 1'h0;
    else if (_002_) count[4] <= _000_[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[1] [0] <= 1'h0;
    else if (_005_) \data_fifo[1] [0] <= wr_data[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[1] [1] <= 1'h0;
    else if (_005_) \data_fifo[1] [1] <= wr_data[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[1] [2] <= 1'h0;
    else if (_005_) \data_fifo[1] [2] <= wr_data[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[1] [3] <= 1'h0;
    else if (_005_) \data_fifo[1] [3] <= wr_data[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[1] [4] <= 1'h0;
    else if (_005_) \data_fifo[1] [4] <= wr_data[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[1] [5] <= 1'h0;
    else if (_005_) \data_fifo[1] [5] <= wr_data[5];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[1] [6] <= 1'h0;
    else if (_005_) \data_fifo[1] [6] <= wr_data[6];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[1] [7] <= 1'h0;
    else if (_005_) \data_fifo[1] [7] <= wr_data[7];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[2] [0] <= 1'h0;
    else if (_006_) \data_fifo[2] [0] <= wr_data[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[2] [1] <= 1'h0;
    else if (_006_) \data_fifo[2] [1] <= wr_data[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[2] [2] <= 1'h0;
    else if (_006_) \data_fifo[2] [2] <= wr_data[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[2] [3] <= 1'h0;
    else if (_006_) \data_fifo[2] [3] <= wr_data[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[2] [4] <= 1'h0;
    else if (_006_) \data_fifo[2] [4] <= wr_data[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[2] [5] <= 1'h0;
    else if (_006_) \data_fifo[2] [5] <= wr_data[5];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[2] [6] <= 1'h0;
    else if (_006_) \data_fifo[2] [6] <= wr_data[6];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[2] [7] <= 1'h0;
    else if (_006_) \data_fifo[2] [7] <= wr_data[7];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[3] [0] <= 1'h0;
    else if (_007_) \data_fifo[3] [0] <= wr_data[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[3] [1] <= 1'h0;
    else if (_007_) \data_fifo[3] [1] <= wr_data[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[3] [2] <= 1'h0;
    else if (_007_) \data_fifo[3] [2] <= wr_data[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[3] [3] <= 1'h0;
    else if (_007_) \data_fifo[3] [3] <= wr_data[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[3] [4] <= 1'h0;
    else if (_007_) \data_fifo[3] [4] <= wr_data[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[3] [5] <= 1'h0;
    else if (_007_) \data_fifo[3] [5] <= wr_data[5];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[3] [6] <= 1'h0;
    else if (_007_) \data_fifo[3] [6] <= wr_data[6];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[3] [7] <= 1'h0;
    else if (_007_) \data_fifo[3] [7] <= wr_data[7];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[4] [0] <= 1'h0;
    else if (_008_) \data_fifo[4] [0] <= wr_data[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[4] [1] <= 1'h0;
    else if (_008_) \data_fifo[4] [1] <= wr_data[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[4] [2] <= 1'h0;
    else if (_008_) \data_fifo[4] [2] <= wr_data[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[4] [3] <= 1'h0;
    else if (_008_) \data_fifo[4] [3] <= wr_data[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[4] [4] <= 1'h0;
    else if (_008_) \data_fifo[4] [4] <= wr_data[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[4] [5] <= 1'h0;
    else if (_008_) \data_fifo[4] [5] <= wr_data[5];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[4] [6] <= 1'h0;
    else if (_008_) \data_fifo[4] [6] <= wr_data[6];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[4] [7] <= 1'h0;
    else if (_008_) \data_fifo[4] [7] <= wr_data[7];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[5] [0] <= 1'h0;
    else if (_009_) \data_fifo[5] [0] <= wr_data[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[5] [1] <= 1'h0;
    else if (_009_) \data_fifo[5] [1] <= wr_data[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[5] [2] <= 1'h0;
    else if (_009_) \data_fifo[5] [2] <= wr_data[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[5] [3] <= 1'h0;
    else if (_009_) \data_fifo[5] [3] <= wr_data[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[5] [4] <= 1'h0;
    else if (_009_) \data_fifo[5] [4] <= wr_data[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[5] [5] <= 1'h0;
    else if (_009_) \data_fifo[5] [5] <= wr_data[5];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[5] [6] <= 1'h0;
    else if (_009_) \data_fifo[5] [6] <= wr_data[6];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[5] [7] <= 1'h0;
    else if (_009_) \data_fifo[5] [7] <= wr_data[7];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[6] [0] <= 1'h0;
    else if (_010_) \data_fifo[6] [0] <= wr_data[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[6] [1] <= 1'h0;
    else if (_010_) \data_fifo[6] [1] <= wr_data[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[6] [2] <= 1'h0;
    else if (_010_) \data_fifo[6] [2] <= wr_data[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[6] [3] <= 1'h0;
    else if (_010_) \data_fifo[6] [3] <= wr_data[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[6] [4] <= 1'h0;
    else if (_010_) \data_fifo[6] [4] <= wr_data[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[6] [5] <= 1'h0;
    else if (_010_) \data_fifo[6] [5] <= wr_data[5];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[6] [6] <= 1'h0;
    else if (_010_) \data_fifo[6] [6] <= wr_data[6];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[6] [7] <= 1'h0;
    else if (_010_) \data_fifo[6] [7] <= wr_data[7];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[7] [0] <= 1'h0;
    else if (_011_) \data_fifo[7] [0] <= wr_data[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[7] [1] <= 1'h0;
    else if (_011_) \data_fifo[7] [1] <= wr_data[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[7] [2] <= 1'h0;
    else if (_011_) \data_fifo[7] [2] <= wr_data[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[7] [3] <= 1'h0;
    else if (_011_) \data_fifo[7] [3] <= wr_data[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[7] [4] <= 1'h0;
    else if (_011_) \data_fifo[7] [4] <= wr_data[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[7] [5] <= 1'h0;
    else if (_011_) \data_fifo[7] [5] <= wr_data[5];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[7] [6] <= 1'h0;
    else if (_011_) \data_fifo[7] [6] <= wr_data[6];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[7] [7] <= 1'h0;
    else if (_011_) \data_fifo[7] [7] <= wr_data[7];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[8] [0] <= 1'h0;
    else if (_012_) \data_fifo[8] [0] <= wr_data[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[8] [1] <= 1'h0;
    else if (_012_) \data_fifo[8] [1] <= wr_data[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[8] [2] <= 1'h0;
    else if (_012_) \data_fifo[8] [2] <= wr_data[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[8] [3] <= 1'h0;
    else if (_012_) \data_fifo[8] [3] <= wr_data[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[8] [4] <= 1'h0;
    else if (_012_) \data_fifo[8] [4] <= wr_data[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[8] [5] <= 1'h0;
    else if (_012_) \data_fifo[8] [5] <= wr_data[5];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[8] [6] <= 1'h0;
    else if (_012_) \data_fifo[8] [6] <= wr_data[6];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[8] [7] <= 1'h0;
    else if (_012_) \data_fifo[8] [7] <= wr_data[7];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[9] [0] <= 1'h0;
    else if (_013_) \data_fifo[9] [0] <= wr_data[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[9] [1] <= 1'h0;
    else if (_013_) \data_fifo[9] [1] <= wr_data[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[9] [2] <= 1'h0;
    else if (_013_) \data_fifo[9] [2] <= wr_data[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[9] [3] <= 1'h0;
    else if (_013_) \data_fifo[9] [3] <= wr_data[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[9] [4] <= 1'h0;
    else if (_013_) \data_fifo[9] [4] <= wr_data[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[9] [5] <= 1'h0;
    else if (_013_) \data_fifo[9] [5] <= wr_data[5];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[9] [6] <= 1'h0;
    else if (_013_) \data_fifo[9] [6] <= wr_data[6];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[9] [7] <= 1'h0;
    else if (_013_) \data_fifo[9] [7] <= wr_data[7];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[10] [0] <= 1'h0;
    else if (_014_) \data_fifo[10] [0] <= wr_data[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[10] [1] <= 1'h0;
    else if (_014_) \data_fifo[10] [1] <= wr_data[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[10] [2] <= 1'h0;
    else if (_014_) \data_fifo[10] [2] <= wr_data[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[10] [3] <= 1'h0;
    else if (_014_) \data_fifo[10] [3] <= wr_data[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[10] [4] <= 1'h0;
    else if (_014_) \data_fifo[10] [4] <= wr_data[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[10] [5] <= 1'h0;
    else if (_014_) \data_fifo[10] [5] <= wr_data[5];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[10] [6] <= 1'h0;
    else if (_014_) \data_fifo[10] [6] <= wr_data[6];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[10] [7] <= 1'h0;
    else if (_014_) \data_fifo[10] [7] <= wr_data[7];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[11] [0] <= 1'h0;
    else if (_015_) \data_fifo[11] [0] <= wr_data[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[11] [1] <= 1'h0;
    else if (_015_) \data_fifo[11] [1] <= wr_data[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[11] [2] <= 1'h0;
    else if (_015_) \data_fifo[11] [2] <= wr_data[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[11] [3] <= 1'h0;
    else if (_015_) \data_fifo[11] [3] <= wr_data[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[11] [4] <= 1'h0;
    else if (_015_) \data_fifo[11] [4] <= wr_data[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[11] [5] <= 1'h0;
    else if (_015_) \data_fifo[11] [5] <= wr_data[5];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[11] [6] <= 1'h0;
    else if (_015_) \data_fifo[11] [6] <= wr_data[6];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[11] [7] <= 1'h0;
    else if (_015_) \data_fifo[11] [7] <= wr_data[7];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[12] [0] <= 1'h0;
    else if (_016_) \data_fifo[12] [0] <= wr_data[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[12] [1] <= 1'h0;
    else if (_016_) \data_fifo[12] [1] <= wr_data[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[12] [2] <= 1'h0;
    else if (_016_) \data_fifo[12] [2] <= wr_data[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[12] [3] <= 1'h0;
    else if (_016_) \data_fifo[12] [3] <= wr_data[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[12] [4] <= 1'h0;
    else if (_016_) \data_fifo[12] [4] <= wr_data[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[12] [5] <= 1'h0;
    else if (_016_) \data_fifo[12] [5] <= wr_data[5];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[12] [6] <= 1'h0;
    else if (_016_) \data_fifo[12] [6] <= wr_data[6];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[12] [7] <= 1'h0;
    else if (_016_) \data_fifo[12] [7] <= wr_data[7];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[13] [0] <= 1'h0;
    else if (_017_) \data_fifo[13] [0] <= wr_data[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[13] [1] <= 1'h0;
    else if (_017_) \data_fifo[13] [1] <= wr_data[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[13] [2] <= 1'h0;
    else if (_017_) \data_fifo[13] [2] <= wr_data[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[13] [3] <= 1'h0;
    else if (_017_) \data_fifo[13] [3] <= wr_data[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[13] [4] <= 1'h0;
    else if (_017_) \data_fifo[13] [4] <= wr_data[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[13] [5] <= 1'h0;
    else if (_017_) \data_fifo[13] [5] <= wr_data[5];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[13] [6] <= 1'h0;
    else if (_017_) \data_fifo[13] [6] <= wr_data[6];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[13] [7] <= 1'h0;
    else if (_017_) \data_fifo[13] [7] <= wr_data[7];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[14] [0] <= 1'h0;
    else if (_018_) \data_fifo[14] [0] <= wr_data[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[14] [1] <= 1'h0;
    else if (_018_) \data_fifo[14] [1] <= wr_data[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[14] [2] <= 1'h0;
    else if (_018_) \data_fifo[14] [2] <= wr_data[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[14] [3] <= 1'h0;
    else if (_018_) \data_fifo[14] [3] <= wr_data[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[14] [4] <= 1'h0;
    else if (_018_) \data_fifo[14] [4] <= wr_data[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[14] [5] <= 1'h0;
    else if (_018_) \data_fifo[14] [5] <= wr_data[5];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[14] [6] <= 1'h0;
    else if (_018_) \data_fifo[14] [6] <= wr_data[6];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[14] [7] <= 1'h0;
    else if (_018_) \data_fifo[14] [7] <= wr_data[7];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[15] [0] <= 1'h0;
    else if (_019_) \data_fifo[15] [0] <= wr_data[0];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[15] [1] <= 1'h0;
    else if (_019_) \data_fifo[15] [1] <= wr_data[1];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[15] [2] <= 1'h0;
    else if (_019_) \data_fifo[15] [2] <= wr_data[2];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[15] [3] <= 1'h0;
    else if (_019_) \data_fifo[15] [3] <= wr_data[3];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[15] [4] <= 1'h0;
    else if (_019_) \data_fifo[15] [4] <= wr_data[4];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[15] [5] <= 1'h0;
    else if (_019_) \data_fifo[15] [5] <= wr_data[5];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[15] [6] <= 1'h0;
    else if (_019_) \data_fifo[15] [6] <= wr_data[6];
  (* src = "uart_tx_combined.v:37.5-73.8" *)
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \data_fifo[15] [7] <= 1'h0;
    else if (_019_) \data_fifo[15] [7] <= wr_data[7];
  assign _135_[3:1] = ip_count[3:1];
  assign _136_[0] = _135_[0];
  assign _137_[3:1] = op_count[3:1];
  assign _138_[0] = _137_[0];
  assign count_out = count;
endmodule
